version: '3.8'

services:
  backend:
    build: ./backend
    container_name: segmentiq_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/app/ml/saved_models:/app/app/ml/saved_models
    environment:
      - PYTHONUNBUFFERED=1
      # Insert your GROQ API key here if utilizing the Llama-3 Generative features
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: always

  frontend:
    build: ./frontend
    container_name: segmentiq_frontend
    ports:
      - "3000:80"  # Exposes the frontend to http://localhost:3000
    depends_on:
      - backend
    restart: always
